### ISSUE TITLE
[Feature Enhancement] Webpage Thumbnail

### ISSUE THREAD

**Issue by JaySMa** [lucaseverett/toolbar-dial#14]
Hello..
Firstly, THANK YOU for an awesome extension.  This has been one of the main issues I haven't given up Opera; the Opera Speed Dial is built-in and is great.  Yours handles this functionality greatly!

My feature request would be a thumbnail creation of the website instead of the title.  Prior versions of Opera had this functionality and it was removed in the around the v5x update chain.  This allows you to "see" the web page without having to visit the page.  Great for when you're searching for a certain website within a folder of multiple pages, and know what the page looks like better than its name.

Thank you again.

**Comment by lucaseverett** [comment]
Thank you for the note! I'm glad you're enjoying using Toolbar Dial. It was because of my interest in changing from Opera to Firefox that I created it!

For the thumbnail request, I know that Vivaldi still uses thumbnails, and I have been considering  adding this feature. I'll put it on my list to implement in a future update!

**Comment by lucaseverett** [comment]
I spent some time looking into this, and there doesn't seem to be a user-friendly and privacy-friendly way to do it.

Firefox and Chrome do offer a way to capture a thumbnail of a webpage, but it actually requires opening a tab to create a thumbnail. So for every bookmark a tab would have to be opened to capture a URL.

Also, that would require use of the "<all_urls>" permission by Toolbar Dial, and that is the most powerful permission an extension can request. It gives an extension the ability to execute a script within any tab -- even one in the background. I don't want to require any permissions other than bookmarks and storage. When I created Toolbar Dial, my mantra from the beginning was to be privacy conscious and never ask for more permissions than necessary to load bookmarks and store settings.

There is another way it could be done, using a third-party API to generate the thumbnail and send it back to the browser, but that would require sharing the URL with the third-party API, and I don't feel comfortable doing that. That would then expose every bookmark you have to a third party service, and that doesn't seem like a very friendly thing for an extension to do.

Considering that, I'm going to close this request. I'll revisit in the future if I come across any technique that would allow this to be done in a privacy-friendly manner.
