### ISSUE TITLE
Columns

### ISSUE THREAD

**Issue by VictorB61** [lucaseverett/toolbar-dial#15]
GREAT dial
I can only have 6 columns. It will work for 3, 4, 5, 6 but when I go above 6 it stays at 6. Won't do 7, 8,....etc. etc.
Am I doing something wrong?. 

Victor

**Comment by lucaseverett** [comment]
Hi @VictorB61,

The columns setting sets the maximum number of columns that could be displayed. However, based on the width of the browser window you may not be able to see that many columns. If you make the window wider, you should be able to go above 6.
