### ISSUE TITLE
Maybe remove google font?

### ISSUE THREAD

**Issue by gitbbnka** [lucaseverett/toolbar-dial#18]
Hello! Toolbar does not load without internet connection. 
Maybe remove google font?

**Comment by lucaseverett** [comment]
Thank you for the comment, @gitbbnka. Will you please provide more details about what is not loading? The font is for the folder icon, so the only part that won't load without an internet connection is the folder icon. Is that what you're referring to?

**Comment by lucaseverett** [comment]
Fixed by #26
