### ISSUE TITLE
[Feature Request] Show folders on top

### ISSUE THREAD

**Issue by NusryNizam** [lucaseverett/toolbar-dial#19]
Hey,
Is it possible to show the folders in the bookmarks show on top (similar to the browser tabs) and to make navigate those folders to find bookmarks in it? And maybe to change tile colors & shape, fonts, font sizes and so on?

Thanks.

**Comment by lucaseverett** [comment]
Thank you for the request. At this time I don't plan to add this feature. I will be adding the option to change color, size, and shape in a future release.
