### ISSUE TITLE
[Future request] Dial color via tags

### ISSUE THREAD

**Issue by regs01** [lucaseverett/toolbar-dial#24]
Is it possible to make dial color customization via bookmark tags? So if there is a tag starting with # and is a valid color, use it. Bookmark tags are fully synced with bookmarks, so it would be fully integrated and wouldn't require any addition storage and options.

**Comment by lucaseverett** [comment]
Hi @regs01! Thank you for the suggestion. Based on my research, it doesn't seem possible for an extension to read bookmark tags. Also, Chrome doesn't have tags, and I want to keep functionality the same between Firefox and Chrome. I do plan to add the ability to customize dial colors soon.

**Comment by regs01** [comment]
I'll leave it here
https://bugzilla.mozilla.org/show_bug.cgi?id=1225916
