### ISSUE TITLE
White placeholders for title even if there is no text

### ISSUE THREAD

**Issue by DaarkWel** [lucaseverett/toolbar-dial#27]
Only visible on other than white backgrounds, pretty annoying.

![image](https://user-images.githubusercontent.com/3049453/120999420-9c775000-c778-11eb-929c-80499fe5b162.png)

Toolbar Dial 2.1 from addons.mozilla.org

**Comment by lucaseverett** [comment]
Hi @DaarkWel! Thank you for the note! I will add an option to hide the title in the next update.

**Comment by lucaseverett** [comment]
Fixed by #32
