### ISSUE TITLE
[Feature request] Add thumbnail option for tiles

### ISSUE THREAD

**Issue by fmaiabatista** [lucaseverett/toolbar-dial#28]
Hi,

First of all, thanks for putting up this extension - I'm coming back to Chrome from Vivaldi and Vivaldi's Speed Dial experience is what I'm missing the most at the moment.

I'd like to ask if there's a future plan to include thumbnails as the tile's images.

Also, I'm a Front-end Developer (React) and I could try to find some spare time to help with small improvements/features since I'm very interested in using the extension myself. :)

**Comment by lucaseverett** [comment]
Hi @fmaiabatista! Thank you for the comment!

I have looked into this in the past year, and there isn't a way to generate site thumbnails that would align with a core philosophy for Toolbar Dial of being privacy friendly. Below is a link to what I found after looking into this last year.

https://github.com/lucaseverett/toolbar-dial/issues/14#issuecomment-637915730

**Comment by fmaiabatista** [comment]
Oh, that's super fair. Thanks for clarifying this and also my bad that I didn't investigate previous closed issues in the repo. I'm closing this one then :)
