### ISSUE TITLE
[Feature Request] Navigate by num keys

### ISSUE THREAD

**Issue by MrNeocore** [lucaseverett/toolbar-dial#30]
When using nested bookmarks, it could be faster to navigate in sub directories and to select [and launch] a bookmark using the numeric keypad.

Exemple:

```
MyBookmarks/
   Sub1/
   Sub2/
      SubSub1/
        url1.bookmarks
        url2.bookmarks
```

url2.bookmarks could be launched using the num keys "command": 1 2 1 2

Thanks for the nice extension ! 
Already helping me making some sense of my too many bookmarks at work :D

**Comment by lucaseverett** [comment]
Thank you for the request. At this time I don't plan to add this feature for num key navigation.
