### ISSUE TITLE
[BUG] Customization open a blank page

### ISSUE THREAD

**Issue by hiranokite** [lucaseverett/toolbar-dial#33]
toolbar-dial 2.3
Windows 11 22000.593
Firefox Nightly 100.0a1
![ff](https://user-images.githubusercontent.com/5361459/161409147-bda00f60-e047-4ff7-950c-61a2c5166402.png)

Customize menu bring a blank page, rolled back to 2.2 and the Customize page load fine!
moz-extension://857f02d7-5fa9-406e-a3a8-455d57d7a91e/options.html

**Comment by lucaseverett** [comment]
Thanks for letting me know! There is a bug in the Firefox addon scanner, and I have to manually rename some files to get around it, and that caused this to happen. I just submitted 2.3.1 to fix this issue.

**Comment by hiranokite** [comment]
Thank you.
