### ISSUE TITLE
Longer bookmark text is left aligned

### ISSUE THREAD

**Issue by SimonWpt** [lucaseverett/toolbar-dial#34]
Longer text for a bookmark is left aligned, because the content of the `div` is wrapped, the `div ` gets 100% width and `justiy-content` from parent doesn't work anymore. Example:

![image](https://user-images.githubusercontent.com/160817/170198038-aacfa4a9-20e1-4b16-a104-6b9624f3918c.png)

The easiest solution should be adding the following line:

```css
text-align: center;
```
in this block

https://github.com/lucaseverett/toolbar-dial/blob/65ac2752230deff5243c5d7710e8031097578042/src/bookmarks/themes/default/Name.js#L34

**Comment by lucaseverett** [comment]
@SimonWpt Thank you for the feedback! I will fix this in the next release.

**Comment by lucaseverett** [comment]
Fixed by fdbd928d76fdf51832f462b48687841997ca9ec0.
