### ISSUE TITLE
feature - remember current folder

### ISSUE THREAD

**Issue by trinajstica** [lucaseverett/toolbar-dial#36]
I just wonder, it's possible to take behaviour from vivaldi browser: if I press home, vivaldi shows current dial (folder), If I reopen vivaldi, it shows last used dial folder... possible to do this?

Thanks!

**Comment by lucaseverett** [comment]
I'm going to have to think about this request. There is a setting to select the default folder that Toolbar Dial uses, and I'm not sure how well that would work if it then reopened the last used folder.

**Comment by lucaseverett** [comment]
I believe I have this working. Would you like to test and make sure it works as expected?

**Comment by trinajstica** [comment]
I will gladly test it.

**Comment by lucaseverett** [comment]
To install, go to about:debugging#/runtime/this-firefox and click the 'Load Temporary Add-on' button. Then select any file in the unzipped folder linked below.

[dist-firefox-beta.zip](https://github.com/toolbar-dial/toolbar-dial/files/9491582/dist-firefox-beta.zip)

**Comment by trinajstica** [comment]
Tested on firefox, It working as expected on all tested links (except facebook, but I have Facebook Container addon, so I disabled it, then it worked ok). That's it! :)

**Comment by lucaseverett** [comment]
Great ! Thank you for the idea and for testing it!

I still have some more work to do for error handling, but this feature will be in version 2.6.

**Comment by trinajstica** [comment]
Thank you! :)

**Comment by lucaseverett** [comment]
Added in 4bb1b06295eb18e00b410df4b7843fa2ab854485
