### ISSUE TITLE
Add page managing

### ISSUE THREAD

**Issue by mrx23dot** [lucaseverett/toolbar-dial#40]
It would be great to add/remove entries via right click menu.

Advanced: edit entry's name/url

without messing with bookmark manager.
See Opera browser for reference.

**Comment by lucaseverett** [comment]
Hi @mrx23dot. Thank you for the comment. You can already delete folders and bookmarks by right click.

I've already started the work to add the ability to edit name/url and hope to have that ready for the next update.

**Comment by lucaseverett** [comment]
Bookmark editing has been added in v2.7 296121b.
