### ISSUE TITLE
file:// Links are not supported

### ISSUE THREAD

**Issue by MagicBertram** [lucaseverett/toolbar-dial#43]
Something like file:///c:/backup/websites/ is currently not supported.

**Comment by lucaseverett** [comment]
Hi @MagicBertram. Thank you for taking the time to file this issue.

This isn't a Toolbar Dial limitation. Browsers don't allow file:// links to be opened from a webpage, and that same limitation applies to web extensions. I filter out file:// links because nothing happens when clicking them.
