### ISSUE TITLE
[FR] deterministic color

### ISSUE THREAD

**Issue by mrx23dot** [lucaseverett/toolbar-dial#46]
Could we make the colors deterministic?

So they would feel the same on different PCs, like I have it installed on 4 different PCs, and colors would help find sites faster.

Something like
`color idx =hash(main domain)[0] % 32`

And some want a manual mode too https://github.com/lucaseverett/toolbar-dial/issues/42
so I guess if not defined in manual mode.

**Comment by lucaseverett** [comment]
Hi @mrx23dot. This is how Toolbar Dial is already set up. It uses a hash to generate a random color that is stable for each domain name. Please let me know if I have misunderstood your message.

**Comment by lucaseverett** [comment]
Yes, that is how it currently works. It generates a random color but the random color is always the same color for each bookmark dial on all computers.

**Comment by lucaseverett** [comment]
Yes, those three are the same, but they're manually set to their colors rather than random. I set a specific color for the top visited domains.

**Comment by lucaseverett** [comment]
I tested that one and it is the same color for me as your screenshot.

**Comment by lucaseverett** [comment]
Thank you for the kind words. I'm glad you enjoy using it. I'm currently working on some enhancements such as being able to manaully set the color of each dial, and the update should be ready in a few weeks.

**Comment by sudoshindo** [comment]
@lucaseverett thoughts on #42 which was mentioned in the first post in this issue thread?

I want the ability to set the colors as well, specially when the brand color doesn't match.

**Comment by lucaseverett** [comment]
Hi @sudoshindo. The ability to set colors will be in the next release, which will be in January.

**Comment by lucaseverett** [comment]
@sudoshindo The demo version now has a beta test for the custom dial color functionality. Please let me know if you have any thoughts or feedback. This will be in the upcoming January update of Toolbar Dial.

https://demo-beta.toolbardial.com/

**Comment by sudoshindo** [comment]
Thank you @lucaseverett for adding the feature.
With this minor inconvenience fixed, I will definitely be swapping to this as my new tab page.

**Comment by sudoshindo** [comment]
@lucaseverett release soon? January is almost over.

**Comment by lucaseverett** [comment]
I'm still working on it. I completely rewrote Toolbar Dial for performance improvements and to make it easier to add new features in the future, and I'm still working on fixing a few issues before releasing the update.

**Comment by sudoshindo** [comment]
Understandable, thanks for the response.
